### ISSUE TITLE
AST and pretty printing

### ISSUE THREAD

**Issue by suhr** [nix-community/rnix-parser#12]
The documentation is inaccurate: `rnix::parser::AST` is a *concrete* syntax tree.

It would be great to be able to create an AST and pretty-print it into a human readable CST.

**Comment by jD91mZM2** [comment]
TIL what a CST is. I think I'll need @matklad's advice on what to do here, I think rather than making an AST we'd want functions to skip over trivia in the CST, which I suppose would have the same effect.

**Comment by lf-** [comment]
I think if you just treat it as a tree of nodes you can print it ignoring all the trivia, probably?

**Comment by jD91mZM2** [comment]
I think that's basically what we're doing?

**Comment by lf-** [comment]
I was under the impression that the Display implementation for the Node would essentially print out the source code directly rather than pretty-printing it.

**Comment by jD91mZM2** [comment]
Ah, right, yes, it's going to include trivia. With the `{:?}` syntax you can print rowan's syntax tree (including trivia). With `TypedNode::dump` you have my favorite representation (including trivia). Anything else, you're going to have to roll your own version of it, using [SyntaxKind::is_trivia](https://docs.rs/rnix/0.8.0/rnix/enum.SyntaxKind.html#method.is_trivia)

**Comment by oberblastmeister** [comment]
`{}` prints the exact source code, `{:#?}` pretty prints as a tree
