### ISSUE TITLE
Cleaning up tests

### ISSUE THREAD

**Issue by darichey** [nix-community/rnix-parser#131]
I think the tests in the crate could use some improvement. It's not clear what the difference is between `test_data/general` and `test_data/parser`, and parser tests are snapshot-based while lexer tests are not

I would like to propose the following:
* Replace the ad-hoc snapshot testing implementation with [expect_test](https://docs.rs/expect-test/latest/expect_test/)
* Make lexer tests snapshot-based
* Reorganize `test_data` like so:
    ```
    test_data/
    ├── parser/
    │   ├── success/
    │   │   ├── assert.nix
    │   │   ├── assert.expect
    │   │   ├── with.nix
    │   │   ├── with.expect
    │   │   └── ...
    │   └── failure/
    │       ├── missing_semi.nix
    │       ├── missing_semi.expect
    │       └── ...
    └── lexer/
        ├── success/
        │   └── ...
        └── failure/
            └── ...
    ```
* Give each test file a meaningful name to indicate what is being tested (so not just `1.nix`)

I am willing to implement the above, but I wanted to get some feedback before starting!

**Comment by oberblastmeister** [comment]
This is very much needed! I will 100% accept all of these changes.
