### ISSUE TITLE
Help: Try type annotations 

### ISSUE THREAD

**Issue by hsjobeki** [nix-community/rnix-parser#155]
### Description

Currently I am working together with some type specialists on a solution for the „types in nix“ problem. I‘d like to try type annotations with rnix. Using rnix to

- Parse the type syntax itself because it is very similar to the nix syntax maybe i could reuse and adopt some parts of the rnix tokenizer and parser.
- Those types integrate with "vanilla" nix natively because they are comments. No Nixel / Nickel / Dahl / etc. required.

But as i am quite new to rnix i would be happy if someone can team up / connect with me ? To have either someone that i could ask questions about rnix.

Current type spec: https://typednix.dev (draft)

**Comment by oberblastmeister** [comment]
@hsjobeki you can go on the matrix server to chat
