### ISSUE TITLE
Parsing NODE_STRING to have TOKEN_WHITESPACE

### ISSUE THREAD

**Issue by Rizary** [nix-community/rnix-parser#16]
Hi,

I am working on nixpkgs-fmt and found this unique behavior on how rnix parse the nix code. For example, I have the following code:
```
{  
  bar = ''
foo
${
  foo
  }
foo
  '';
}
```

when I parse the code, I notice that between `{` and `bar`, the parsing result would be:
```
NODE_ROOT 0..569 {
  NODE_ATTR_SET 0..568 {
    TOKEN_CURLY_B_OPEN("{") 0..1
    TOKEN_WHITESPACE("\n    ") 1..2
    NODE_KEY_VALUE 2..93 {
      NODE_KEY 2..5 {
        NODE_IDENT 2..5 {
          TOKEN_IDENT("foo") 2..5
        }
      }
```

We have `TOKEN_WHITESPACE` in between the `{` and the `bar`. However, for every `TOKEN_STRING_CONTENT` whitespace is included in 1 token. Is this intended behavior? Personally, it is little inconsistent, for example the above code will result:
```
TOKEN_STRING_START("\'\'") 103..105
 TOKEN_STRING_CONTENT("\nfoo\n") 105..110
```

But if I have the following code:
```
  baz =
    ''
      foo
      ${
```

then the parsing result is:
```
NODE_STRING 148..305 {
  TOKEN_STRING_START("\'\'") 148..150
  TOKEN_STRING_CONTENT("\n      foo\n      ") 150..167
```

And if we add spaceafter the `"` (4 times for example), the token parsed as:
```
TOKEN_STRING_START("\'\'") 154..156
TOKEN_STRING_CONTENT("          \n      foo\n      ") 156..183
```

In my view,  the string content is the `foo` itself and not whitespace/newline in between. 

What do you think?

**Comment by layus** [comment]
In my prototype of enriched multiline strings (https://github.com/NixOS/nix/pull/580, to automatically reindent the antiquotation at the same level as the opening `${`), I found that the most simple way to work with multiline strings is a sequences indented one-line string content.

Here is an example of my mental model for a multiline string:

```
    ''      some text
   foo
     ${bar}
 '';
```


```
node multiline-string {
  node multiline-string-line {
    token whitespace "    "
	token string-content "  some text"
  }
  node multiline-string-line {
	token whitespace "    "
	token string-content "foo"
  }
  node multiline-string-line {
    token whitespace "    "
    token string-content "  "
	node /* something about the ${bar} */
  }
  node multiline-string-line {
	token whitespace "    "
  }
}
```

Having the lines already spitted by rnix, and the correct level of indent to strip already identified would help a lot to reindent such strings, and identify correctly cases where the first and/or last line is not taken into account. (a whitespace-only first line is ignored, a premature ending on the last line does not limit the indent to strip from each line, etc.)

Of course, this means that there is more work to perform when closing the multiline-string node, as the indent level for the lines cannot be computed before.

PS: Note that I am not too sure where to place the newline. In the string or in the whitespace ? Logically, it belongs to both.

**Comment by Rizary** [comment]
Regarding newline, what I am thinking right now is to put it inside the `TOKEN_WHITESPACE`. It is because if I have the following code:
```
{
  foo = 
    ...
    for i in ${env}/* /host/*; do
      path="/''${i##*/}"
      [ -e "$path" ]
    ...
  '';
}
```

Then I'll have the following code:
```
TOKEN_STRING_CONTENT("/* /host/*; do\n      path=\"/\'\'${i##*/}\"\n      [ -e \"$path\" ] || ")
```

Which in my point of view, separating the `\n` from content is the best way to detect previous block of it, like in `\n      path`, we can detect whether the previous path has newline or not.

@layus anyway, thanks for the `multiline-string` idea, I hope I can have the idea on how rnix-parser works within this week.

**Comment by Rizary** [comment]
The original of the above example is:
```
{
  foo = run: writeScript "${name}-init" ''
    #! ${stdenv.shell}
    for i in ${env}/* /host/*; do
      path="/''${i##*/}"
      [ -e "$path" ] || ${coreutils}/bin/ln -s "$i" "$path"
    done
    [ -d "$1" ] && [ -r "$1" ] && cd "$1"
    shift
    source /etc/profile
    exec ${run} "$@"
  '';
}
```

**Comment by layus** [comment]
I have a (hacky) first attempt at a patch (https://github.com/nix-community/rnix-parser/compare/master...layus:string_lines/first). For my example it gives:

```
NODE_ROOT 0..47 {
  TOKEN_WHITESPACE("     ") 0..5
  NODE_STRING 5..47 {
    TOKEN_STRING_START("\'\'") 5..7
    NODE_STRING_LINE 7..21 {
      TOKEN_STRING_CONTENT("     test data") 7..21
    }
    NODE_STRING_LINE 21..29 {
      TOKEN_STRING_CONTENT("\n    foo") 21..29
    }
    NODE_STRING_LINE 29..42 {
      TOKEN_STRING_CONTENT("\n      ") 29..36
      NODE_STRING_INTERPOL 36..42 {
        TOKEN_INTERPOL_START("${") 36..38
        NODE_IDENT 38..41 {
          TOKEN_IDENT("bar") 38..41
        }
        TOKEN_INTERPOL_END("}") 41..42
      }
    }
    NODE_STRING_LINE 42..45 {
      TOKEN_STRING_CONTENT("\n  ") 42..45
    }
    TOKEN_STRING_END("\'\'") 45..47
  }
}
```

It is not exactly suited to your needs. I think you do not care about the NODE_STRING_LINE, but you do need a TOKEN_WHITESPACE on each line. Not sure yet how to do that.

**Comment by layus** [comment]
I managed to extract the leading spaces. I had to use TOKEN_INDENT because TOKEN_WHITESPACE is `trivia` and invisible to the parser:

```
NODE_ROOT 0..47 {
  TOKEN_WHITESPACE("     ") 0..5
  NODE_STRING 5..47 {
    TOKEN_STRING_START("\'\'") 5..7
    NODE_STRING_LINE 7..21 {
      TOKEN_INDENT("     ") 7..12
      TOKEN_STRING_CONTENT("test data") 12..21
    }
    NODE_STRING_LINE 21..29 {
      TOKEN_INDENT("\n    ") 21..26
      TOKEN_STRING_CONTENT("foo") 26..29
    }
    NODE_STRING_LINE 29..42 {
      TOKEN_INDENT("\n      ") 29..36
      NODE_STRING_INTERPOL 36..42 {
        TOKEN_INTERPOL_START("${") 36..38
        NODE_IDENT 38..41 {
          TOKEN_IDENT("bar") 38..41
        }
        TOKEN_INTERPOL_END("}") 41..42
      }
    }
    NODE_STRING_LINE 42..45 {
      TOKEN_INDENT("\n  ") 42..45
    }
    TOKEN_STRING_END("\'\'") 45..47
  }
}
```

the NODE_STRING_LINE is optional:

```
NODE_ROOT 0..47 {
  TOKEN_WHITESPACE("     ") 0..5
  NODE_STRING 5..47 {
    TOKEN_STRING_START("\'\'") 5..7
    TOKEN_INDENT("     ") 7..12
    TOKEN_STRING_CONTENT("test data") 12..21
    TOKEN_INDENT("\n    ") 21..26
    TOKEN_STRING_CONTENT("foo") 26..29
    TOKEN_INDENT("\n      ") 29..36
    NODE_STRING_INTERPOL 36..42 {
      TOKEN_INTERPOL_START("${") 36..38
      NODE_IDENT 38..41 {
        TOKEN_IDENT("bar") 38..41
      }
      TOKEN_INTERPOL_END("}") 41..42
    }
    TOKEN_INDENT("\n  ") 42..45
    TOKEN_STRING_END("\'\'") 45..47
  }
}
```

Not yet sure how to extract the exact indent, but working on it :-)

**Comment by layus** [comment]
After some thinking, it looks really difficult to update the green tree. There is a replace_with method, that returns a new root when called on a node. A bit frustrating since it would be trivial to edit a node before it's insertions in the tree (during finish_node()) but rowan does not support that. Is there any chance to get something merged in rowan ?

@jD91mZM2, any idea on this topic ?

**Comment by Rizary** [comment]
This is awsome! I'll try it today. 
> 
> Not yet sure how to extract the exact indent, but working on it :-)

I think the above result is similar on the current parser for nix code outside node string. 

I'm not sure we need node_string_line but I might be wrong. 

About the whitespace, for just clarity, token_string_whitespace is also good name actually.

**Comment by layus** [comment]
Have a look at https://github.com/nix-community/rnix-parser/compare/master...layus:string_lines/second or https://github.com/nix-community/rnix-parser/compare/master...layus:string_lines/third if you do not want the NODE_STRING_LINE

**Comment by Rizary** [comment]
I tried with the `string_lines/third` branch and found this code:
```
''
  bar/${foo}/baz/
  ${
    quux
  }
''
```

get parsed with nixpkgs-fmt `--parse` command into:

```
  NODE_STRING 0..42 {
    TOKEN_STRING_START("\'\'") 0..2
    TOKEN_INDENT("\n  ") 2..5
    TOKEN_STRING_CONTENT("bar/") 5..9
    NODE_STRING_INTERPOL 9..15 {
      TOKEN_INTERPOL_START("${") 9..11
      NODE_IDENT 11..14 {
        TOKEN_IDENT("foo") 11..14
      }
      TOKEN_INTERPOL_END("}") 14..15
    }
    TOKEN_ERROR("") 15..15
    TOKEN_STRING_CONTENT("/baz/") 15..20
    TOKEN_INDENT("\n") 20..21
    TOKEN_STRING_CONTENT("\n  ") 21..24
    NODE_STRING_INTERPOL 24..39 {
      TOKEN_INTERPOL_START("${") 24..26
      TOKEN_WHITESPACE("\n    ") 26..31
      NODE_IDENT 31..35 {
        TOKEN_IDENT("quux") 31..35
      }
      TOKEN_WHITESPACE("\n  ") 35..38
      TOKEN_INTERPOL_END("}") 38..39
    }
    TOKEN_INDENT("\n") 39..40
    TOKEN_STRING_END("\'\'") 40..42
  }
  TOKEN_WHITESPACE("\n\n") 42..44
}
```

The usual parser will have `TOKEN_WHITESPACE("\n\n    ")` if we put newline twice.

**Comment by Rizary** [comment]
Got another case with:
```
{
postFixup =  ''
        cd $out/clion-${version}
        rm -rf bin/cmake/linux
        ln -s ${cmake} bin/cmake/linux

        lldbLibPath=$out/clion-${version}/bin/lldb/linux/lib
        interp="$(cat $NIX_CC/nix-support/dynamic-linker)"
      '';
}
```

and I got:
```
TOKEN_INDENT("\n") 120..121
TOKEN_STRING_CONTENT("\n        lldbLibPath=$out/clion-")
```

**Comment by jD91mZM2** [comment]
Sorry for the delay! I'm a little torn between whether or not this should be the parser's job. While writing this I was initially just thinking strings should be completely as-is, including whitespace and all that. I would certainly not decline a PR though, and I think @layus has done excellent work so far. Both in his work to rnix-parser and also the brilliant https://github.com/NixOS/nix/pull/580 PR which I really hope gets merged.

CC @matklad

**Comment by layus** [comment]
> Got another case with:

Just to be clear, this is the intended behavior. I split every line, and mark the leading space with an optional preceding line break as TOKEN_INDENT. I can do something else, but it needs to be specified. I particular, spaces are meaningful in indented lines:

```
⋅⋅''
⋅⋅⋅⋅test
⋅⋅⋅⋅⋅⋅
⋅⋅⋅''
```
is `"test\n⋅⋅\n"` because there remains two spaces after stripping the indent.

The more I think about this, the less clear it is to me what to do with these indented strings. In nix itself, the value is modified by the parser within the grammar. I am investigating a way to do this in rowan, but it is clearly not designed to support that.

**Comment by Rizary** [comment]
@layus I see, that's make sense. Noted, thank you.
@jD91mZM2 hmm interesting. I am not sure if there is any guideline on how parser do and don't, so I might be wrong to open this issue. 

The problem is when I am working on `nixpkgs-fmt`, I notice that I am having 2 for loops just to fix the node string. I am not sure if it is correct or not though.

Well, I am still investigating from my end. So, if the way rnix-parser or parser in common should behave like the current state, then I might look from another angle to fix `nixpkgs-fmt` issue.

**Comment by jD91mZM2** [comment]
> @jD91mZM2 hmm interesting. I am not sure if there is any guideline on how parser do and don't, so I might be wrong to open this issue.

@Rizary You are **not** wrong to open this issue, it's an interesting question that'll need contemplating!

> After some thinking, it looks really difficult to update the green tree.
> ...
> I am investigating a way to do this in rowan, but it is clearly not designed to support that.

@layus I'd be happy to take a look if you can show me what you're trying to do and why it doesn't work. Perhaps we just need to look at things a different way, @matklad thinks AST mutations are rarely needed so perhaps we can make it work without them.

**Comment by layus** [comment]
@jD91mZM2 The main thing that does not work is to find out what I want, and what should be performed. Are the leading spaces in an indented string part of the string, or part of the whitespaces ?

Thinking about this twice, it seems that trying to change rnix is too much of a hassle with unclear benefits and requirements. It should be quite feasible to handle indented strings as-is in nix-format.

**Comment by Rizary** [comment]
Just to update about this, I am going to close the issue since part of `nixpkgs-fmt` approach on `NODE_STRING` is different from the other node. So, even though we make `NODE_STRING` like `TOKEN_WHITESPACE`, it doesn't solved the entire problem we are facing while formatting `NODE_STRING`
