### ISSUE TITLE
Converge the token names towards the ones used in nix

### ISSUE THREAD

**Issue by zimbatm** [nix-community/rnix-parser#2]
This is a bit of a meta ticket.

The idea is that if the token names are close to each-other, it will be easier to compare and update the syntax if it ever changes upstream.

[Link to lexer.l](https://github.com/nixos/nix/blob/f435634a29551754d5f7303b0a60cd8fe2df2079/src/libexpr/lexer.l)

* [ ] PATH, SPATH and HPATH. rnix only has path and I am not entirely convinced the regexp is the same
* [ ] the lexer is using shorter names such as EQ, LEQ, ...

**Comment by zimbatm** [comment]
it would be nice if nix could emit it's AST so that both could be compared

**Comment by zimbatm** [comment]
@matklad was interested in taking a look as well

**Comment by zimbatm** [comment]
As mentioned by @matklad in https://github.com/nix-community/rnix-parser/pull/4#issuecomment-527852726 , the nix parser produces an AST which is quite different.

**Comment by jD91mZM2** [comment]
Is this still relevant after the latest batch of PRs and 0.7.0?

**Comment by zimbatm** [comment]
Happy to close it
