### ISSUE TITLE
Doesn't parse valid Nix edge-cases

### ISSUE THREAD

**Issue by puckipedia** [nix-community/rnix-parser#23]
`let b = a: a; "or" = 5; in  [b or]` fails to be properly parsed, and instead generates a partial `NODE_OR_DEFAULT` and errors.

This seems to also influence other bits, e.g. `[b or b]` parses as a valid `NODE_OR_DEFAULT`, while it is actually parsed as `[(b or) b]` by Nix.

**Comment by jD91mZM2** [comment]
Ah, I see. So `or` is really a function (whose name is suffixed) that takes a default value as argument?

I assume `(5 +) 3` doesn't work though, as it does in Haskell? Just checking - I am on phone currently

**Comment by jD91mZM2** [comment]
No wait wtf, it only works when it's `or`.

```nix
let
  inc = n: n + 1;

  number = 3;
  or = 3;
in
{
  inc_number = [ inc number ];
  inc_or = [ inc or ];
}
```

pls send help

**Comment by zimbatm** [comment]
in nixpkgs/lib/default.nix we also encounter this issue: https://github.com/NixOS/nixpkgs/blob/810d22fb35287e14125470e3b917b90488ae5ed5/lib/default.nix#L67

Minimal repro:
```nix
let
  inherit (builtins) a b c d or e;
in
null
```

**Comment by Ma27** [comment]
Self-assigning here as this is something we should tackle at some point. Please note that getting out a new rnix-lsp release soon has a higher priority for me and I only have a fairly limited time budget for maintaining rnix* :)

**Comment by NerdyPepper** [comment]
@Ma27 I'd be happy to help work on this crate, or atleast close off loose ends, I am using it for a couple of projects. Is there a matrix/irc channel where the maintainers coordinate?

**Comment by Ma27** [comment]
We usually use `#rnix-lsp:matrix.org`, but since rnix-lsp and rnix-parser are both maintained by the same folks currently (primarily Aaron and me), it's perfectly fine to use it :)

**Comment by Ma27** [comment]
I'd consider this to be a tracking issue now for 1.0 where we should try to be equivalent to Nix's parser. That said, minor things can be done in the next release I'd plan, 0.10.

**Comment by aaronjanse** [comment]
> can we like, uh, just ignore this and pretend it's a bug in nix? i am confused

Please. I'm strongly in favor of changing this in the official nix parser. Of course, if upstream refuses to make the change, then we should also implement the ~~bug~~ feature to match the reference implementation

**Comment by L-as** [comment]
> > can we like, uh, just ignore this and pretend it's a bug in nix? i am confused
> 
> Please. I'm strongly in favor of changing this in the official nix parser. Of course, if upstream refuses to make the change, then we should also implement the ~bug~ feature to match the reference implementation

Changing the language backwards incompatibly is a hard no-go IMO. Doesn't matter how stupid the design is. You're going to break supposedly hermetic flakes. If you want to fix this, you should propose a mechanism for introducing new versions of the language à la Rust editions or something along those lines.
