### ISSUE TITLE
Node creation

### ISSUE THREAD

**Issue by DieracDelta** [nix-community/rnix-parser#25]
Suppose I want to create an `AttrSet` programmatically. This isn't very easy to do with the current API. The easiest thing to do is to create a string, parse it, and cast the root node to an AttrSet. This feels a bit hacky.

Thoughts on adding in constructors to `src/types.rs` that add in constructors for the various nodes? For example, something like:

```
  pub fn new(k: String) -> Key {...}
  pub fn new(k: Key, v: SyntaxNode) -> KeyValue {...}
  pub fn new(kvs: Vec<KeyValue>) -> AttrSet {...}
 ```
 
The idea is that these would add in all of the tokens necessary to make this syntactically valid. If there's interest, I can probably implement this, as we need it anyway for [flake generator](https://github.com/DieracDelta/flake_generator).

**Comment by DieracDelta** [comment]
So, I've taken a stab at this. I'm not sure if there's an easier way that I'm just missing, but what I had in mind live in [here](https://github.com/DieracDelta/flake_generator/blob/feat/node_insertion/src/parser/input_utils.rs#L22). If this makes sense and seems like a good idea, I can pull together a draft PR.

**Comment by NerdyPepper** [comment]
[rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) has an [AST creation module here](https://rust-analyzer.github.io/rust-analyzer/syntax/ast/make/index.html). They do exactly what you suggested: create a minimal nix source file with the node kind, parse to tree, find it, and cast.

**Comment by DieracDelta** [comment]
Wow this is seemingly what I was looking for. Thanks!
