### ISSUE TITLE
implement fmt::Debug (and other traits) for ParsedTypeError

### ISSUE THREAD

**Issue by pandaman64** [nix-community/rnix-parser#26]
Currently, [`rnix::types::ParsedTypeError`](https://docs.rs/rnix/0.9.0/rnix/types/struct.ParsedTypeError.html) does not implement any traits.
As a result, it is impossible to write `ParsedType::try_from(node).unwrap()` because [`Result::unwrap` requires the error type to implement `fmt::Debug`](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap).

**Comment by Ma27** [comment]
Fixed in #41.
