### ISSUE TITLE
Move to a monorepo setup

### ISSUE THREAD

**Issue by matklad** [nix-community/rnix-parser#3]
@zimbatm @jD91mZM2 what do you think about merging `rnix`, `nixpkgs-fmt` (and maybe nix-lsp as well?) into a single repositroy?

I suggest the following setup:

```
repo: https://github.com/nix-community/rnix

Cargo.toml // a workspace file
crates/
  parser/  <- rnix-parser
  fmt/ // <- the library part of current nixpkgs-fmt
  nixpkgs-fmt/  <- the binary part of nixpkgs-fmt
  web/ <- wasm webpage stuff
```

**Comment by matklad** [comment]
I think this can be done with preserving the git history of all subrepos

**Comment by zimbatm** [comment]
Is there a convention like in Go to put all the bin packages in a cmd/ folder? I think we'll have many more binaries if we go down that route.

**Comment by matklad** [comment]
Nope, there's no specific convention. I was also thinking about

```
Cargo.toml
  lib/
    parser/
    fmt/
  bin/
    nixpkgs-fmt/
    lsp/
    web/
```

**Comment by jD91mZM2** [comment]
I wish GitHub would let you create sub-groups - I don't like monorepos :(

If it's OK with you, I'd prefer making it painfully obvious that rnix is not limited to the formatter or the lsp (by having it separate), and that everyone can and should use rnix for all their things.

**Comment by matklad** [comment]
Yeah, I don't have a super-strong opinion about monorepo vs polyrepo at this scale, keeping things separate is fine with me as well!
