### ISSUE TITLE
Diversion from nix with splices in paths

### ISSUE THREAD

**Issue by nerdypepper** [nix-community/rnix-parser#44]
### Describe the bug

Splicing/antiquoting in paths results in a syntax error, whereas Nix permits templated paths.

### Code Snippet to reproduce

```nix
let
  x = "abc";
in
  ./${x}
```

### Expected behavior

The nix file is valid and should successfully evaluate to something like `/home/np/abc`.

**Comment by Ma27** [comment]
FYI I'm actively working on this now.
