### ISSUE TITLE
[ci proposal] add cargo fmt  -- --check

### ISSUE THREAD

**Issue by efx** [nix-community/rnix-parser#50]
### Description

As a developer I value the consistency `cargo fmt` provides to Rust codebases.
I propose we add `cargo fmt -- --check` to the `test.yml` workflow.

### Considered alternatives

- do not do this
  - not enforcing consistency goes against the grain of Rust's ethos
- automated `cargo fmt` applying
  - I find this overly complex.   

### Additional context

- where should this go?
  - https://github.com/nix-community/rnix-parser/blob/65fbe7ac947af2d6c794ca04d1316b5b9bca8a9e/flake.nix#L35

**Comment by Ma27** [comment]
Makes sense, but I'd prefer to get most of the other changes merged before to avoid forcing people to resolve conflicts.

**Comment by efx** [comment]
> I'd prefer to get most of the other changes merged before to avoid forcing people to resolve conflicts

Great plan! 

I'm in no rush too. I can take a crack at this in the coming weeks / months.

**Comment by darichey** [comment]
I think this can be closed now (github didn't link it to the PR)
