### ISSUE TITLE
improve documentation of `value::Anchor`

### ISSUE THREAD

**Issue by zseri** [nix-community/rnix-parser#68]
Currently, `Anchor` is defined like this:
```rust
pub enum Anchor {
    Absolute,
    Relative,
    Home,
    Store,
}
```
What the `Absolute` and `Relative` kinds mean is imo clear.
But `Home` and especially `Store` are non-obvious.
* `Home` resolves to `~/`
* `Store` is used for Nix angle-paths, e.g. `<nixpkgs>`, usually resolved via the environment variable `NIX_PATH`. I don't think the name of this anchor really fits.

## Suggestion
```rust
pub enum Anchor {
    Absolute,
    Relative,

    /// Anchor for paths relative to `~/`, usually resolved via
    /// the environment variable `HOME` or such.
    Home,

    /// Anchor for [Nix angle-paths](https://nixos.org/guides/nix-pills/nix-search-paths.html),
    /// e.g. `<nixpkgs>`, usually resolved via iterating through the environment variable `NIX_PATH`.
    Store,
}
```

**Comment by Ma27** [comment]
Seems reasonable to me. Feel free to open a PR with these changes :)
