### ISSUE TITLE
Correctly strip away trailing white-space on the left in multi-line strings

### ISSUE THREAD

**Issue by Ma27** [nix-community/rnix-parser#71]
### Describe the bug

As pointed out by @zimbatm in #67, the indentation of multi-line strings blindly includes all the indentation event though it's stripped away by the reference implementation of the Nix parser.

### Code Snippet to reproduce

```nix
''
  foo
  bar
''
```

```
$ nix-instantiate --parse foo.nix
"foo\nbar\n"
$ cargo run --example dump-ast foo.nix
NODE_ROOT 0..18 {
  NODE_STRING 0..17 {
    TOKEN_STRING_START("\'\'") 0..2
    TOKEN_STRING_CONTENT("\n  foo\n  bar\n") 2..15
    TOKEN_STRING_END("\'\'") 15..17
  }
  TOKEN_WHITESPACE("\n") 17..18
}
```

### Expected behavior

The problematic part is the `  ` before `foo` and `bar` that is actually stripped away.

### Additional context

see #67

**Comment by zimbatm** [comment]
Also reminder: Nix only counts spaces as indents, not tabs.

The big question is what shape the parsed tokens should look like. I guess if we want to keep this a CST, it should be something like:
```
NODE_ROOT 0..18 {
  NODE_STRING 0..17 {
    TOKEN_STRING_START("\'\'") 0..2
    TOKEN_WHITESPACE("\n   ") # Or should we introduce a TOKEN_INDENT?
    TOKEN_STRING_CONTENT("foo\n")
    TOKEN_WHITESPACE("  ")
    TOKEN_STRING_CONTENT("bar\n")
    TOKEN_STRING_END("\'\'") 15..17
  }
  TOKEN_WHITESPACE("\n") 17..18
}
```

**Comment by kamadorueda** [comment]
Just a philosophical question: Is it rnix-parser responsibility to dedent? would it make things more simple not to worry about dedenting and instead returning the raw string content? would it make the parser more correct in the art of parsing to leave such dedenting to the tools (if any) that actually require such specialized post-processing?

From the use cases I have seen, the rnix-parser is used in:
- Formatters, which implement the dedenting/indenting logic themselves
- Writting linters, which do not care about the indent 
- Documentation generators, based on comments
- Static analyzers which find dead code

So if it helps, or makes the parser more simple to maintain, or more correct, it could be a good idea to drop the feature

**Comment by kamadorueda** [comment]
> Do you think that the current behavior is actually useful for e.g. a formatter like Alejandra

The current behavior (not removing the indent) is useful, and removing the indent would also be useful, but it's not a critical feature for Alejandra

> can you explain why the parser would be more correct if it leaves the indent

Implementing a feature may introduce new bugs,  make parsing slower, or introduce more code to test and maintain in the future, so sometimes fewer features are also good

**Comment by Ma27** [comment]
> Implementing a feature may introduce new bugs

I think it's kinda problematic to argue like this here: yes, less code is better, OTOH this is a parser that produce a "correct" result, of course the question is how we define "correct" in this case - as you correctly stated in your previous comment.

> The current behavior (not removing the indent) is useful, and removing the indent would also be useful, but it's not a critical feature for Alejandra

So to correctly understand you, we'd not be breaking Alejandra badly if we implement this? Because, I'm still in favor of doing that because I consider this to be a step of the parsing process :)

**Comment by oberblastmeister** [comment]
It's not the job of the parser to strip away whitespace, as we are trying to be a full-fidelity parser. Stripping the whitespace is part of the *semantics*, not *syntax*, so should be implemented as a method on `Str` after parsing. In fact, I think this is already done in `str_util.rs`.
