### ISSUE TITLE
Handle `true`, `false` ?

### ISSUE THREAD

**Issue by dmadisetti** [nix-community/rnix-parser#81]
it seems to me that they are primitives and should be castable to `rnix::value::Value::Boolean`

**Comment by aaronjanse** [comment]
Note that `true` can be a variable name:
```
nix-repl> let true = 7; in true
7
```

**Comment by dmadisetti** [comment]
Right, I found out in #83

I think this is pretty disappointing. What would thoughts be on removing TOKEN_BOOL, but keeping the conversation? I guess I can implement this out of the library. It's just annoying

**Comment by darichey** [comment]
I don't think there's anything the parser should do here. `true`, `false`, and `null` are essentially variable names which are bound at the top level to their corresponding values, but those names can be shadowed like any other (see [reference impl](https://github.com/NixOS/nix/blob/63df0fda94b60719fd1db13fa42422d0835561ad/src/libexpr/primops.cc#L3893-L3900)). Therefore, the distinction must be made during evaluation.

**Comment by Ma27** [comment]
I agree with @darichey here.
