### ISSUE TITLE
Path prefix stripping

### ISSUE THREAD

**Issue by darichey** [nix-community/rnix-parser#90]
Consider the program:
```rust
use rnix::types::{Wrapper, Value, TypedNode};

fn main() {
    for expr in ["/foo", "./foo", "~/foo", "<foo>"] {
        let v = rnix::parse(expr).root().inner().and_then(Value::cast).unwrap().to_value().unwrap();
        println!("{v:?}");
    }
}
```
which produces the output:
```
Path(Absolute, "/foo")
Path(Relative, "./foo")
Path(Home, "foo")
Path(Store, "foo")
```
Is it intentional/desired that the Absolute and Relative paths retain their prefixes while the Home and Store paths do not?

**Comment by Ma27** [comment]
@darichey not sure if I understand the question. Which prefix would you expect to be removed by e.g. an absolute path?

**Comment by darichey** [comment]
My initial thought would be that they should all be just `"foo"`, and then the Anchor essentially tells you the base path. But actually, I guess Anchor already does that, it just wasn't the base path I expected! For example, if I just always prepend the cwd to a Relative path, I might get a redundant `foo/./bar`, but since I will need to canonicalize the path anyways, it doesn't really matter.

I don't think anything needs to change :)
